# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pcap_quizzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(490, 490, 75, 23))
        self.next_button.setObjectName("next_button")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(250, 490, 75, 23))
        self.previous_button.setObjectName("previous_button")
        self.answer_a_label = QtWidgets.QLabel(self.centralwidget)
        self.answer_a_label.setGeometry(QtCore.QRect(250, 290, 361, 31))
        self.answer_a_label.setObjectName("answer_a_label")
        self.answer_b_label = QtWidgets.QLabel(self.centralwidget)
        self.answer_b_label.setGeometry(QtCore.QRect(250, 330, 381, 31))
        self.answer_b_label.setObjectName("answer_b_label")
        self.answer_c_label = QtWidgets.QLabel(self.centralwidget)
        self.answer_c_label.setGeometry(QtCore.QRect(250, 370, 381, 31))
        self.answer_c_label.setObjectName("answer_c_label")
        self.answer_d_label = QtWidgets.QLabel(self.centralwidget)
        self.answer_d_label.setGeometry(QtCore.QRect(250, 410, 361, 31))
        self.answer_d_label.setObjectName("answer_d_label")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(60, 40, 651, 231))
        self.question.setObjectName("question")
        self.copyright_label = QtWidgets.QLabel(self.centralwidget)
        self.copyright_label.setGeometry(QtCore.QRect(680, 540, 121, 20))
        self.copyright_label.setObjectName("copyright_label")
        self.radio_button_a = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button_a.setGeometry(QtCore.QRect(230, 300, 82, 17))
        self.radio_button_a.setObjectName("radio_button_a")
        self.radio_button_b = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button_b.setGeometry(QtCore.QRect(230, 330, 82, 17))
        self.radio_button_b.setObjectName("radio_button_b")
        self.radio_button_c = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button_c.setGeometry(QtCore.QRect(230, 380, 82, 17))
        self.radio_button_c.setObjectName("radio_button_c")
        self.radio_button_d = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_button_d.setGeometry(QtCore.QRect(230, 420, 82, 17))
        self.radio_button_d.setObjectName("radio_button_d")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 540, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.timer_label = QtWidgets.QLabel(self.centralwidget)
        self.timer_label.setGeometry(QtCore.QRect(740, 0, 47, 13))
        self.timer_label.setObjectName("timer_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuPCAP_Quizzer = QtWidgets.QMenu(self.menubar)
        self.menuPCAP_Quizzer.setObjectName("menuPCAP_Quizzer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPCAP_Quizzer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.answer_a_label.setText(_translate("MainWindow", "answer_a"))
        self.answer_b_label.setText(_translate("MainWindow", "answer_b"))
        self.answer_c_label.setText(_translate("MainWindow", "answer_c"))
        self.answer_d_label.setText(_translate("MainWindow", "answer_d"))
        self.question.setText(_translate("MainWindow", "                                                                                               question"))
        self.copyright_label.setText(_translate("MainWindow", "(c) Hauke Juri Schnepel"))
        self.radio_button_a.setText(_translate("MainWindow", "RadioButton"))
        self.radio_button_b.setText(_translate("MainWindow", "RadioButton"))
        self.radio_button_c.setText(_translate("MainWindow", "RadioButton"))
        self.radio_button_d.setText(_translate("MainWindow", "RadioButton"))
        self.timer_label.setText(_translate("MainWindow", "TextLabel"))
        self.menuPCAP_Quizzer.setTitle(_translate("MainWindow", "PCAP Quizzer"))
